version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    # you can use image or custom build below
    #image: nabo.codimd.dev/hackmdio/hackmd:2.0.0
    #image: hackmdio/codimd
    image: liascript/codilia:latest
    # build:
    #   context: ..
    #   dockerfile: ./deployments/Dockerfile
    environment:
      - CMD_DB_URL=postgres://codimd:change_password@database/codimd
      - CMD_USECDN=false
      - CMD_ALLOW_ANONYMOUS=true
      # - CMD_SHARE_URL=https://LiaScript.github.io/course/?https://yourserver,running.codi.md
      # - CMD_RESPONSIVEVOICE_KEY=12345678
      # - CMD_DOMAIN=localhost:4000
    depends_on:
      - database
    ports:
      - "4000:3000"
    volumes:
      - upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
